name: Build Pansou
on: 
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Build
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -v -o pansou main.go
      - name: Package
        run: |
          tar -czvf pansou-linux.tar.gz pansou
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: pansou-linux.tar.gz
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
